---
  - name: restart bind
    become: True
    service: name=bind9 state=restarted enabled=yes

  - name: restart manual-notify
    become: True
    service: name=manual-notify state=restarted enabled=yes

  - name: reload aa-profile
    become: True
    command: apparmor_parser -r /etc/apparmor.d/usr.sbin.named
